// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7kbMUWXKnK_0e_22xXbS7frSGMX94Xn0',
    appId: '1:2616789504:web:28a0d1c88fd2cde5ed66e5',
    messagingSenderId: '2616789504',
    projectId: 'fl-cosmiatria',
    authDomain: 'fl-cosmiatria.firebaseapp.com',
    storageBucket: 'fl-cosmiatria.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0kCwHPLQA2RxmA2gtlKZKoAxe8u3eChM',
    appId: '1:2616789504:android:770a58b945dcff88ed66e5',
    messagingSenderId: '2616789504',
    projectId: 'fl-cosmiatria',
    storageBucket: 'fl-cosmiatria.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5WrItRtu5y8Hgbtav6nLb33FgDEys87M',
    appId: '1:2616789504:ios:15724130535548afed66e5',
    messagingSenderId: '2616789504',
    projectId: 'fl-cosmiatria',
    storageBucket: 'fl-cosmiatria.appspot.com',
    iosBundleId: 'com.example.flCosmiatria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5WrItRtu5y8Hgbtav6nLb33FgDEys87M',
    appId: '1:2616789504:ios:9e25a7d207b6412eed66e5',
    messagingSenderId: '2616789504',
    projectId: 'fl-cosmiatria',
    storageBucket: 'fl-cosmiatria.appspot.com',
    iosBundleId: 'com.example.flCosmiatria.RunnerTests',
  );
}
